services:
  letterbox:
    image: ghcr.io/nobisindustries/letterbox:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    env_file:
      - .env
    restart: unless-stopped
