"""initial schema

Revision ID: 97fdc4ef4986
Revises: 
Create Date: 2026-03-09 13:31:41.751632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97fdc4ef4986'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sender', sa.Text(), nullable=True),
    sa.Column('receiver', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('raw_llm_response', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('letter_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['letter_id'], ['letters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # FTS5 virtual table and sync triggers
    op.execute("""
        CREATE VIRTUAL TABLE letters_fts USING fts5(
            title, summary, sender, receiver, keywords, full_text,
            content='letters', content_rowid='id'
        )
    """)
    op.execute("""
        CREATE TRIGGER letters_ai AFTER INSERT ON letters BEGIN
            INSERT INTO letters_fts(rowid, title, summary, sender, receiver, keywords, full_text)
            VALUES (new.id, new.title, new.summary, new.sender, new.receiver, new.keywords, new.full_text);
        END
    """)
    op.execute("""
        CREATE TRIGGER letters_ad AFTER DELETE ON letters BEGIN
            INSERT INTO letters_fts(letters_fts, rowid, title, summary, sender, receiver, keywords, full_text)
            VALUES ('delete', old.id, old.title, old.summary, old.sender, old.receiver, old.keywords, old.full_text);
        END
    """)
    op.execute("""
        CREATE TRIGGER letters_au AFTER UPDATE ON letters BEGIN
            INSERT INTO letters_fts(letters_fts, rowid, title, summary, sender, receiver, keywords, full_text)
            VALUES ('delete', old.id, old.title, old.summary, old.sender, old.receiver, old.keywords, old.full_text);
            INSERT INTO letters_fts(rowid, title, summary, sender, receiver, keywords, full_text)
            VALUES (new.id, new.title, new.summary, new.sender, new.receiver, new.keywords, new.full_text);
        END
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS letters_au")
    op.execute("DROP TRIGGER IF EXISTS letters_ad")
    op.execute("DROP TRIGGER IF EXISTS letters_ai")
    op.execute("DROP TABLE IF EXISTS letters_fts")
    op.drop_table('tasks')
    op.drop_table('letters')
    # ### end Alembic commands ###
